apiVersion: v1
kind: Pod
metadata:
  name: astra-backend
spec:
  containers:
  - name: astra-backend
    image: astra-backend
    ports:
        - containerPort: 9999
        - containerPort: 5678
    envFrom:
    - configMapRef:
        name: env-config
